### ISSUE TITLE
Add jwt token check optionally to services

### ISSUE THREAD

**Issue by dioptre** [sfproductlabs/roo#1]
This will be a replacement for client SSL certificates.

Also - publish my work on ajwt

**Comment by joe-getcouragenow** [comment]
Did anything come of this ?

You might be interested is this: https://github.com/authelia/authelia
Solves a ton of work for JWT and login etc etc

**Comment by dioptre** [comment]
Ah looks interesting, I'll be implementing our internal jwt sso system first. I haven't published it yet, but should play nicely with what you might have already if you are using jwt. I'll let you know when I get started on it.

**Comment by dioptre** [comment]
Also mate, if you have any input on what you might want/need let me know!

**Comment by dioptre** [comment]
The more I think about it, the feature might be useless. You'd have to overwrite the fetch method on websites to include the cookie. This could easily be done with a browser extension but I'm not certain it's worth the effort?

**Comment by dioptre** [comment]
Or perhaps, when the first request is made, we could setup a socket, and if the socket closes, terminate the proxy or something like that... gotta think about it.

**Comment by joe-getcouragenow** [comment]
this looks useful : https://github.com/greenpau/caddy-auth-portal

they will add https://github.com/authelia/authelia soon also to it.

**Comment by dioptre** [comment]
I still think it doesn't solve the proxy request for passing tokens through? Ex. I use a service called 'superset' a spark based analytics platform on cassandra. I'd like to force-pass the jwt to the proxy so that it can pass through the request to superset, but unless superset fetch requests on the front end (or a browser plugin forces it, or some kind of pre-existing websocket handshake allow us to setup the request), i'm not sure if we can use this approach?

**Comment by dioptre** [comment]
It may be too difficult to support for every use case, so closing this after investigating it.
